##### Copyright 2019 The TensorFlow Authors.

# Overview

https://www.tensorflow.org/

https://www.tensorflow.org/overview/

https://www.tensorflow.org/hub

https://www.tensorflow.org/install

https://www.tensorflow.org/install/gpu

https://www.tensorflow.org/learn

https://www.tensorflow.org/guide/eager

https://www.tensorflow.org/guide/tensor

You will hear `logits`.
Logits also refer to the element-wise inverse of the sigmoid function. 
>The vector of raw (non-normalized) predictions that a classification model generates, which is ordinarily then passed to a normalization function. If the model is solving a multi-class classification problem, logits typically become an input to the softmax function. The softmax function then generates a vector of (normalized) probabilities with one value for each possible class.

In [2]:
import os

import tensorflow as tf

import cProfile

In [3]:
tf.executing_eagerly()

True

In [4]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [6]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1

In [8]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TensorFlow 2 quickstart for beginners

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This short introduction uses [Keras](https://www.tensorflow.org/guide/keras/overview) to:

1. Build a neural network that classifies images.
2. Train this neural network.
3. And, finally, evaluate the accuracy of the model.

This is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook file. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

1. In Colab, connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*.
2. Run all the notebook code cells: Select *Runtime* > *Run all*.

Download and install TensorFlow 2. Import TensorFlow into your program:

Note: Upgrade `pip` to install the TensorFlow 2 package. See the [install guide](https://www.tensorflow.org/install) for details.

In [2]:
import tensorflow as tf

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Convert the samples from integers to floating-point numbers:

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Build the `tf.keras.Sequential` model by stacking layers. Choose an optimizer and loss function for training:

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Reference
<p style="font-family: Arial; font-size:1.2em;color:blue;">
Details of <a href = "https://www.tensorflow.org/api_docs/python/tf/keras/Sequential">Sequential Model</a>. Sequential provides training and inference features on this model.
</p>

<p style="font-family: Arial; font-size:1.2em;color:blue;">You can also instantiate a Model with the <strong>"Functional API"</strong>, where you start from Input, you chain layer calls to specify the model's forward pass, and finally you create your model from inputs and outputs:

>import tensorflow as tf

>inputs = tf.keras.Input(shape=(3,))
>x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)

>outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)

>model = tf.keras.Model(inputs=inputs, outputs=outputs)

    
<p style="font-family: Arial; font-size:1.2em;color:green;">You can also extend the model class, if love to live by sword!!

For each example the model returns a vector of "[logits](https://developers.google.com/machine-learning/glossary#logits)" or "[log-odds](https://developers.google.com/machine-learning/glossary#log-odds)" scores, one for each class.

In [6]:
# whats in first row of data....
x_train[:1].shape

(1, 28, 28)

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.1062777 ,  0.27161902, -0.06621724, -0.15404087, -0.08236469,
         0.18122366, -0.6639569 , -0.19976473, -0.05792055,  0.688342  ]],
      dtype=float32)

In [8]:
predictions.sum()

-0.189358

The `tf.nn.softmax` function converts these logits to "probabilities" for each class: 

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.08652637, 0.12626034, 0.09006302, 0.08249074, 0.08862042,
        0.11534765, 0.04953949, 0.07880388, 0.09081335, 0.19153468]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy().sum()

0.99999994

Note: It is possible to bake this `tf.nn.softmax` in as the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to
provide an exact and numerically stable loss calculation for all models when using a softmax output. 

<p style="font-family: Arial; font-size:1.2em;color:blue;">
    Softmax function is prone to two issues: overflow and underflow.<br>
    <strong>Overflow</strong> occurs when very large numbers are being fed. <strong>Underflow</strong> occurs when very small numbers (near zero) are being fed.<br>
There are work arounds too, but, TF has its own approach.<br>

    Intution being that every system (32 / 64 bit precision) has limits interms of largest or smallest value it can accurately process.<br>
    It also leads to the vanishing gradient in exponential functions. As you go higher/lower the  will overflow and the gradient will be 0 irrespective of actually it being non 0.

The `losses.SparseCategoricalCrossentropy` loss takes a vector of logits and a `True` index and returns a scalar loss for each example.

<p style="font-family: Arial; font-size:1.2em;color:blue;">
    Use this cross entropy loss function when there are two or more label classes. We expect labels to be provided as integers. If you want to provide labels using <span style="color:red;">one-hot</span> representation, please use <strong style="color:red;">CategoricalCrossentropy</strong> loss. There should be # classes floating point values per feature for y_pred and a single floating point value per feature for y_true.
<p style="font-family: Arial; font-size:1.2em;color:blue;">
In the snippet below, there is a single floating point value per example for y_true and # classes floating pointing values per example for y_pred. The shape of y_true is [batch_size] and the shape of y_pred is [batch_size, num_classes]
    
>y_true = [1, 2]<br>
>y_pred = [ [0.05, 0.95, 0], [0.1, 0.8, 0.1] ]

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the the true class:
It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.log(1/10) ~= 2.3`.

In [1]:
y_train[:1]

NameError: name 'y_train' is not defined

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.1598048

Using `model.compile`, We specify the training configuration such as:
- Loss function to minimize
- Optimizer
- List of metrics to monitor

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

<p style="font-family: Arial; font-size:1.2em;color:blue;">
    We call fit(), which will train the model by slicing the data into "batches" of size "batch_size", and repeatedly iterating over the entire dataset for a given number of "epochs". We pass some validation for monitoring validation loss and metrics at the end of each epoch.

The `Model.fit` method adjusts the model parameters to minimize the loss: 

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2954 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1438 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1057 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0878 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0755 - accuracy: 0.9765


<p style="font-family: Arial; font-size:1.2em;color:blue;">Output above indicates that it is returning some object. History object to be more precise. This object can be used to track progress of epochs. The returned "history" object holds a record of the loss values and metric values during training:

The `Model.evaluate` method checks the models performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)".

In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0734 - accuracy: 0.9763


[0.07342638075351715, 0.9763000011444092]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8606372e-07, 2.6250115e-08, 1.3928508e-06, 3.6284477e-05,
        2.1241705e-11, 3.5212732e-08, 1.3062632e-13, 9.9996138e-01,
        3.6590649e-07, 3.6999484e-07],
       [6.8427491e-10, 1.6910373e-05, 9.9996543e-01, 1.5217093e-05,
        1.3726618e-14, 1.9253762e-06, 4.4088903e-08, 7.5549559e-14,
        4.9705710e-07, 1.1683626e-11],
       [1.0010299e-06, 9.9860543e-01, 4.7720572e-05, 4.4354169e-06,
        1.1948595e-04, 1.3909009e-06, 1.0425796e-04, 9.1225526e-04,
        1.9718474e-04, 6.8162021e-06],
       [9.9991119e-01, 2.3360819e-08, 2.8288803e-05, 7.6732323e-07,
        3.4976173e-07, 3.2104315e-06, 1.9863912e-05, 2.5126939e-05,
        1.3965940e-08, 1.1201703e-05],
       [4.1336584e-06, 2.7645364e-09, 2.1263595e-05, 6.3611901e-07,
        9.7798651e-01, 9.6138444e-07, 6.7118490e-06, 6.4558582e-05,
        3.9159167e-06, 2.1911403e-02]], dtype=float32)>